/**
 * Entity Seed Data - بيانات الجهات والخبراء الأولية
 * Run with: npx tsx src/seeds/entitySeed.ts
 *
 * SAFE: Only inserts if entities table is empty. Never deletes or modifies existing data.
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ENTITIES_SEED = [
  {
    name: 'وزارة الاستثمار',
    nameEn: 'Ministry of Investment',
    role: 'جهة حكومية رسمية',
    type: 'ministry',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=MISA&background=0D47A1&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 245000,
    postsCount: 1240,
    datasetsCount: 45,
    specialties: JSON.stringify(['الاستثمار الأجنبي', 'التراخيص', 'الفرص الاستثمارية', 'المناطق الاقتصادية']),
    description: 'الجهة المسؤولة عن تنظيم وتطوير بيئة الاستثمار في المملكة وجذب الاستثمارات الأجنبية المباشرة',
    website: 'misa.gov.sa',
    establishedYear: '2020',
    impact: 'critical',
  },
  {
    name: 'الهيئة العامة للإحصاء',
    nameEn: 'General Authority for Statistics',
    role: 'جهة حكومية رسمية',
    type: 'authority',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=GASTAT&background=1B5E20&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 189000,
    postsCount: 2850,
    datasetsCount: 120,
    specialties: JSON.stringify(['البيانات الإحصائية', 'المسوحات الوطنية', 'مؤشرات الاقتصاد', 'سوق العمل']),
    description: 'المصدر الرسمي للبيانات والإحصاءات الوطنية، توفر بيانات دقيقة وموثوقة لدعم اتخاذ القرار',
    website: 'stats.gov.sa',
    establishedYear: '1960',
    impact: 'critical',
  },
  {
    name: 'البنك المركزي السعودي',
    nameEn: 'Saudi Central Bank (SAMA)',
    role: 'جهة حكومية رسمية',
    type: 'authority',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=SAMA&background=B71C1C&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 312000,
    postsCount: 980,
    datasetsCount: 65,
    specialties: JSON.stringify(['السياسة النقدية', 'الاستقرار المالي', 'الرقابة المصرفية', 'الاحتياطيات']),
    description: 'البنك المركزي للمملكة، المسؤول عن السياسة النقدية والرقابة على القطاع المصرفي والمالي',
    website: 'sama.gov.sa',
    establishedYear: '1952',
    impact: 'critical',
  },
  {
    name: 'وزارة التجارة',
    nameEn: 'Ministry of Commerce',
    role: 'جهة حكومية رسمية',
    type: 'ministry',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=MC&background=E65100&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 156000,
    postsCount: 1560,
    datasetsCount: 38,
    specialties: JSON.stringify(['السجلات التجارية', 'حماية المستهلك', 'التجارة الإلكترونية', 'الملكية الفكرية']),
    description: 'تنظيم وتطوير الأنشطة التجارية وحماية حقوق المستهلكين وتعزيز بيئة الأعمال',
    website: 'mc.gov.sa',
    establishedYear: '1954',
    impact: 'high',
  },
  {
    name: 'هيئة السوق المالية',
    nameEn: 'Capital Market Authority',
    role: 'جهة حكومية رسمية',
    type: 'authority',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=CMA&background=4A148C&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 198000,
    postsCount: 1120,
    datasetsCount: 52,
    specialties: JSON.stringify(['سوق الأسهم', 'الشركات المدرجة', 'الإفصاحات', 'الرقابة المالية']),
    description: 'تنظيم وتطوير السوق المالية السعودية وحماية المستثمرين والمتعاملين',
    website: 'cma.org.sa',
    establishedYear: '2003',
    impact: 'critical',
  },
  {
    name: 'وزارة الطاقة',
    nameEn: 'Ministry of Energy',
    role: 'جهة حكومية رسمية',
    type: 'ministry',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=MOE&background=1B5E20&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 142000,
    postsCount: 890,
    datasetsCount: 42,
    specialties: JSON.stringify(['الطاقة المتجددة', 'النفط والغاز', 'الكهرباء', 'الاستدامة']),
    description: 'تنظيم قطاع الطاقة وتطوير مصادر الطاقة المتجددة وضمان أمن الإمداد',
    website: 'moenergy.gov.sa',
    establishedYear: '2019',
    impact: 'critical',
  },
  {
    name: 'وزارة الموارد البشرية والتنمية الاجتماعية',
    nameEn: 'Ministry of Human Resources',
    role: 'جهة حكومية رسمية',
    type: 'ministry',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=HRSD&background=6A1B9A&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 280000,
    postsCount: 1890,
    datasetsCount: 55,
    specialties: JSON.stringify(['سوق العمل', 'التوظيف', 'نظام العمل', 'التنمية الاجتماعية']),
    description: 'تنظيم سوق العمل وتطوير القوى العاملة ودعم برامج التنمية الاجتماعية',
    website: 'hrsd.gov.sa',
    establishedYear: '2019',
    impact: 'critical',
  },
  {
    name: 'الهيئة العامة للعقار',
    nameEn: 'Real Estate General Authority',
    role: 'جهة حكومية رسمية',
    type: 'authority',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://ui-avatars.com/api/?name=REGA&background=00695C&color=fff&size=200&bold=true',
    coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=400&fit=crop',
    isVerified: true,
    verificationLevel: 'official',
    followersCount: 95000,
    postsCount: 680,
    datasetsCount: 28,
    specialties: JSON.stringify(['تنظيم القطاع العقاري', 'التراخيص العقارية', 'المؤشرات العقارية', 'الوساطة']),
    description: 'تنظيم وتطوير القطاع العقاري غير الحكومي ورفع كفاءته وحوكمته',
    website: 'rega.gov.sa',
    establishedYear: '2017',
    impact: 'high',
  },
  {
    name: 'د. خالد بن فهد العثمان',
    nameEn: 'Dr. Khalid Al-Othman',
    role: 'خبير اقتصادي - محلل أسواق',
    type: 'expert',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=khalid',
    isVerified: true,
    verificationLevel: 'verified',
    followersCount: 45200,
    postsCount: 1850,
    specialties: JSON.stringify(['الاقتصاد الكلي', 'الأسواق المالية', 'رؤية 2030', 'التحليل الاستراتيجي']),
    description: 'خبير اقتصادي معتمد مع أكثر من 15 عاماً من الخبرة في تحليل الأسواق السعودية والخليجية',
    impact: 'high',
  },
  {
    name: 'سارة المنصور',
    nameEn: 'Sarah Al-Mansour',
    role: 'محللة بيانات عقارية',
    type: 'analyst',
    location: 'جدة، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=sarah',
    isVerified: true,
    verificationLevel: 'verified',
    followersCount: 28500,
    postsCount: 920,
    specialties: JSON.stringify(['السوق العقاري', 'تحليل البيانات', 'التقييم العقاري', 'الاستثمار العقاري']),
    description: 'متخصصة في تحليل بيانات السوق العقاري السعودي وتقديم رؤى استثمارية دقيقة',
    impact: 'high',
  },
  {
    name: 'م. عبدالله الجارالله',
    nameEn: 'Eng. Abdullah Al-Jarallah',
    role: 'خبير سلاسل الإمداد واللوجستيات',
    type: 'expert',
    location: 'الدمام، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=abdullah',
    isVerified: true,
    verificationLevel: 'verified',
    followersCount: 32800,
    postsCount: 1240,
    specialties: JSON.stringify(['سلاسل الإمداد', 'اللوجستيات', 'التجارة الدولية', 'الموانئ']),
    description: 'مهندس صناعي متخصص في تحسين سلاسل الإمداد وتطوير الحلول اللوجستية',
    impact: 'high',
  },
  {
    name: 'أحمد محمود الشهري',
    nameEn: 'Ahmed Al-Shehri',
    role: 'محلل تقني - أسواق المال',
    type: 'analyst',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=ahmed',
    isVerified: false,
    verificationLevel: 'none',
    followersCount: 18300,
    postsCount: 2450,
    specialties: JSON.stringify(['التحليل الفني', 'تاسي', 'العملات الرقمية', 'الأسهم']),
    description: 'محلل تقني متخصص في أسواق الأسهم السعودية والخليجية',
    impact: 'medium',
  },
  {
    name: 'د. نورة العتيبي',
    nameEn: 'Dr. Noura Al-Otaibi',
    role: 'خبيرة اقتصاد كلي',
    type: 'expert',
    location: 'الرياض، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=noura',
    isVerified: true,
    verificationLevel: 'verified',
    followersCount: 52100,
    postsCount: 1680,
    specialties: JSON.stringify(['الاقتصاد الكلي', 'السياسة المالية', 'التضخم', 'النمو الاقتصادي']),
    description: 'أستاذة الاقتصاد في جامعة الملك سعود، متخصصة في دراسات الاقتصاد السعودي',
    impact: 'high',
  },
  {
    name: 'فهد الدوسري',
    nameEn: 'Fahad Al-Dosari',
    role: 'محلل قطاع الطاقة',
    type: 'analyst',
    location: 'الظهران، المملكة العربية السعودية',
    avatar: 'https://i.pravatar.cc/200?u=fahad',
    isVerified: true,
    verificationLevel: 'verified',
    followersCount: 38700,
    postsCount: 1120,
    specialties: JSON.stringify(['أسواق النفط', 'الطاقة المتجددة', 'أوبك', 'تحليل القطاع']),
    description: 'محلل متخصص في قطاع الطاقة السعودي والعالمي مع خبرة تزيد عن 10 سنوات',
    impact: 'high',
  },
];

async function seed() {
  // SAFETY: Only seed if entities table is empty
  const existingCount = await prisma.entity.count();
  if (existingCount > 0) {
    console.log(`ℹ️ Entities table already has ${existingCount} records. Skipping seed.`);
    return;
  }

  console.log('🌱 Seeding entities...');

  await prisma.entity.createMany({
    data: ENTITIES_SEED,
  });

  const total = await prisma.entity.count();
  console.log(`✅ Seeded ${total} entities`);
}

seed()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
