/**
 * Seed Signals - DISABLED
 *
 * This file has been disabled because ALL signals must come from REAL data.
 * NO MOCK/FAKE DATA ALLOWED.
 *
 * Real signals are generated by:
 * - src/services/realSignalGenerator.ts (from actual dataset statistics)
 * - src/services/aiAnalysis.ts (from OpenAI analysis of real data)
 */

import { logger } from '../utils/logger.js';

async function seedSignals() {
  logger.info('seedSignals is DISABLED - All signals must come from real data');
  logger.info('Use /api/signals/analyze or /api/admin/trigger/analysis to generate real signals');
  return;
}

// Run - does nothing now
seedSignals()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
